# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('basic-sim-main-full', ['basic-sim'])
    obj.source = 'main_full.cc'
