# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('basic-sim-example-single-flows', ['basic-sim'])
    obj.source = 'single_flows.cc'

    obj = bld.create_ns3_program('basic-sim-example-single-pingmesh', ['basic-sim'])
    obj.source = 'single_pingmesh.cc'
